FROM oven/bun:1-alpine AS base

ENV NODE_ENV=production
WORKDIR /node

# =========================================================================== #
FROM base AS builder

COPY . .

RUN bun install -g turbo
RUN turbo prune frontend --docker

# =========================================================================== #
FROM base AS installer

COPY --from=builder /node/out/json/ ./
RUN bun install
COPY --from=builder /node/out/full/ .

WORKDIR /node/apps/frontend

ARG VITE_BACKEND_BASE_URL
RUN echo "VITE_BACKEND_BASE_URL=${VITE_BACKEND_BASE_URL}" > .env

RUN NODE_OPTIONS="--max-old-space-size=768" bun run build

# =========================================================================== #
FROM caddy:2-alpine AS production

COPY --from=installer /node/apps/frontend/caddyfile /etc/caddy/caddyfile
COPY --from=installer /node/apps/frontend/dist /srv

EXPOSE 80

CMD ["caddy", "run", "--config", "/etc/caddy/caddyfile"]
