export type ChemicalElement = {
	atomicNumber: number;
	symbol: string;
	name: string;
	atomicMass: number;
	category: string;
	group: number | null;
	period: number;
	block: string;
	electronConfiguration: string;
	density: number | null;
	meltingPoint: number | null;
	boilingPoint: number | null;
	discoveryYear: number | null;
};

export const chemicalElements: ChemicalElement[] = [
	{
		atomicNumber: 1,
		symbol: "H",
		name: "Hydrogen",
		atomicMass: 1.008,
		category: "Nonmetal",
		group: 1,
		period: 1,
		block: "s",
		electronConfiguration: "1s¹",
		density: 0.00008988,
		meltingPoint: 14.01,
		boilingPoint: 20.28,
		discoveryYear: 1766,
	},
	{
		atomicNumber: 2,
		symbol: "He",
		name: "Helium",
		atomicMass: 4.003,
		category: "Noble Gas",
		group: 18,
		period: 1,
		block: "s",
		electronConfiguration: "1s²",
		density: 0.0001785,
		meltingPoint: null,
		boilingPoint: 4.22,
		discoveryYear: 1868,
	},
	{
		atomicNumber: 3,
		symbol: "Li",
		name: "Lithium",
		atomicMass: 6.941,
		category: "Alkali Metal",
		group: 1,
		period: 2,
		block: "s",
		electronConfiguration: "[He] 2s¹",
		density: 0.534,
		meltingPoint: 453.69,
		boilingPoint: 1615,
		discoveryYear: 1817,
	},
	{
		atomicNumber: 4,
		symbol: "Be",
		name: "Beryllium",
		atomicMass: 9.012,
		category: "Alkaline Earth Metal",
		group: 2,
		period: 2,
		block: "s",
		electronConfiguration: "[He] 2s²",
		density: 1.85,
		meltingPoint: 1560,
		boilingPoint: 2742,
		discoveryYear: 1798,
	},
	{
		atomicNumber: 5,
		symbol: "B",
		name: "Boron",
		atomicMass: 10.811,
		category: "Metalloid",
		group: 13,
		period: 2,
		block: "p",
		electronConfiguration: "[He] 2s² 2p¹",
		density: 2.34,
		meltingPoint: 2349,
		boilingPoint: 4200,
		discoveryYear: 1808,
	},
	{
		atomicNumber: 6,
		symbol: "C",
		name: "Carbon",
		atomicMass: 12.011,
		category: "Nonmetal",
		group: 14,
		period: 2,
		block: "p",
		electronConfiguration: "[He] 2s² 2p²",
		density: 2.267,
		meltingPoint: 3823,
		boilingPoint: 4098,
		discoveryYear: null,
	},
	{
		atomicNumber: 7,
		symbol: "N",
		name: "Nitrogen",
		atomicMass: 14.007,
		category: "Nonmetal",
		group: 15,
		period: 2,
		block: "p",
		electronConfiguration: "[He] 2s² 2p³",
		density: 0.0012506,
		meltingPoint: 63.15,
		boilingPoint: 77.36,
		discoveryYear: 1772,
	},
	{
		atomicNumber: 8,
		symbol: "O",
		name: "Oxygen",
		atomicMass: 15.999,
		category: "Nonmetal",
		group: 16,
		period: 2,
		block: "p",
		electronConfiguration: "[He] 2s² 2p⁴",
		density: 0.001429,
		meltingPoint: 54.36,
		boilingPoint: 90.2,
		discoveryYear: 1774,
	},
	{
		atomicNumber: 9,
		symbol: "F",
		name: "Fluorine",
		atomicMass: 18.998,
		category: "Halogen",
		group: 17,
		period: 2,
		block: "p",
		electronConfiguration: "[He] 2s² 2p⁵",
		density: 0.001696,
		meltingPoint: 53.53,
		boilingPoint: 85.03,
		discoveryYear: 1886,
	},
	{
		atomicNumber: 10,
		symbol: "Ne",
		name: "Neon",
		atomicMass: 20.18,
		category: "Noble Gas",
		group: 18,
		period: 2,
		block: "p",
		electronConfiguration: "[He] 2s² 2p⁶",
		density: 0.0008999,
		meltingPoint: 24.56,
		boilingPoint: 27.07,
		discoveryYear: 1898,
	},
	{
		atomicNumber: 11,
		symbol: "Na",
		name: "Sodium",
		atomicMass: 22.99,
		category: "Alkali Metal",
		group: 1,
		period: 3,
		block: "s",
		electronConfiguration: "[Ne] 3s¹",
		density: 0.971,
		meltingPoint: 370.87,
		boilingPoint: 1156,
		discoveryYear: 1807,
	},
	{
		atomicNumber: 12,
		symbol: "Mg",
		name: "Magnesium",
		atomicMass: 24.305,
		category: "Alkaline Earth Metal",
		group: 2,
		period: 3,
		block: "s",
		electronConfiguration: "[Ne] 3s²",
		density: 1.738,
		meltingPoint: 923,
		boilingPoint: 1363,
		discoveryYear: 1755,
	},
	{
		atomicNumber: 13,
		symbol: "Al",
		name: "Aluminum",
		atomicMass: 26.982,
		category: "Post-Transition Metal",
		group: 13,
		period: 3,
		block: "p",
		electronConfiguration: "[Ne] 3s² 3p¹",
		density: 2.698,
		meltingPoint: 933.47,
		boilingPoint: 2792,
		discoveryYear: 1825,
	},
	{
		atomicNumber: 14,
		symbol: "Si",
		name: "Silicon",
		atomicMass: 28.086,
		category: "Metalloid",
		group: 14,
		period: 3,
		block: "p",
		electronConfiguration: "[Ne] 3s² 3p²",
		density: 2.3296,
		meltingPoint: 1687,
		boilingPoint: 3538,
		discoveryYear: 1824,
	},
	{
		atomicNumber: 15,
		symbol: "P",
		name: "Phosphorus",
		atomicMass: 30.974,
		category: "Nonmetal",
		group: 15,
		period: 3,
		block: "p",
		electronConfiguration: "[Ne] 3s² 3p³",
		density: 1.82,
		meltingPoint: 317.3,
		boilingPoint: 550,
		discoveryYear: 1669,
	},
	{
		atomicNumber: 16,
		symbol: "S",
		name: "Sulfur",
		atomicMass: 32.065,
		category: "Nonmetal",
		group: 16,
		period: 3,
		block: "p",
		electronConfiguration: "[Ne] 3s² 3p⁴",
		density: 2.067,
		meltingPoint: 388.36,
		boilingPoint: 717.87,
		discoveryYear: null,
	},
	{
		atomicNumber: 17,
		symbol: "Cl",
		name: "Chlorine",
		atomicMass: 35.453,
		category: "Halogen",
		group: 17,
		period: 3,
		block: "p",
		electronConfiguration: "[Ne] 3s² 3p⁵",
		density: 0.003214,
		meltingPoint: 171.6,
		boilingPoint: 239.11,
		discoveryYear: 1774,
	},
	{
		atomicNumber: 18,
		symbol: "Ar",
		name: "Argon",
		atomicMass: 39.948,
		category: "Noble Gas",
		group: 18,
		period: 3,
		block: "p",
		electronConfiguration: "[Ne] 3s² 3p⁶",
		density: 0.0017837,
		meltingPoint: 83.8,
		boilingPoint: 87.3,
		discoveryYear: 1894,
	},
	{
		atomicNumber: 19,
		symbol: "K",
		name: "Potassium",
		atomicMass: 39.098,
		category: "Alkali Metal",
		group: 1,
		period: 4,
		block: "s",
		electronConfiguration: "[Ar] 4s¹",
		density: 0.862,
		meltingPoint: 336.53,
		boilingPoint: 1032,
		discoveryYear: 1807,
	},
	{
		atomicNumber: 20,
		symbol: "Ca",
		name: "Calcium",
		atomicMass: 40.078,
		category: "Alkaline Earth Metal",
		group: 2,
		period: 4,
		block: "s",
		electronConfiguration: "[Ar] 4s²",
		density: 1.54,
		meltingPoint: 1115,
		boilingPoint: 1757,
		discoveryYear: 1808,
	},
	{
		atomicNumber: 21,
		symbol: "Sc",
		name: "Scandium",
		atomicMass: 44.956,
		category: "Transition Metal",
		group: 3,
		period: 4,
		block: "d",
		electronConfiguration: "[Ar] 3d¹ 4s²",
		density: 2.989,
		meltingPoint: 1814,
		boilingPoint: 3109,
		discoveryYear: 1879,
	},
	{
		atomicNumber: 22,
		symbol: "Ti",
		name: "Titanium",
		atomicMass: 47.867,
		category: "Transition Metal",
		group: 4,
		period: 4,
		block: "d",
		electronConfiguration: "[Ar] 3d² 4s²",
		density: 4.54,
		meltingPoint: 1941,
		boilingPoint: 3560,
		discoveryYear: 1791,
	},
	{
		atomicNumber: 23,
		symbol: "V",
		name: "Vanadium",
		atomicMass: 50.942,
		category: "Transition Metal",
		group: 5,
		period: 4,
		block: "d",
		electronConfiguration: "[Ar] 3d³ 4s²",
		density: 6.11,
		meltingPoint: 2183,
		boilingPoint: 3680,
		discoveryYear: 1801,
	},
	{
		atomicNumber: 24,
		symbol: "Cr",
		name: "Chromium",
		atomicMass: 51.996,
		category: "Transition Metal",
		group: 6,
		period: 4,
		block: "d",
		electronConfiguration: "[Ar] 3d⁵ 4s¹",
		density: 7.15,
		meltingPoint: 2180,
		boilingPoint: 2944,
		discoveryYear: 1797,
	},
	{
		atomicNumber: 25,
		symbol: "Mn",
		name: "Manganese",
		atomicMass: 54.938,
		category: "Transition Metal",
		group: 7,
		period: 4,
		block: "d",
		electronConfiguration: "[Ar] 3d⁵ 4s²",
		density: 7.44,
		meltingPoint: 1519,
		boilingPoint: 2334,
		discoveryYear: 1774,
	},
	{
		atomicNumber: 26,
		symbol: "Fe",
		name: "Iron",
		atomicMass: 55.845,
		category: "Transition Metal",
		group: 8,
		period: 4,
		block: "d",
		electronConfiguration: "[Ar] 3d⁶ 4s²",
		density: 7.874,
		meltingPoint: 1811,
		boilingPoint: 3134,
		discoveryYear: null,
	},
	{
		atomicNumber: 27,
		symbol: "Co",
		name: "Cobalt",
		atomicMass: 58.933,
		category: "Transition Metal",
		group: 9,
		period: 4,
		block: "d",
		electronConfiguration: "[Ar] 3d⁷ 4s²",
		density: 8.86,
		meltingPoint: 1768,
		boilingPoint: 3200,
		discoveryYear: 1735,
	},
	{
		atomicNumber: 28,
		symbol: "Ni",
		name: "Nickel",
		atomicMass: 58.693,
		category: "Transition Metal",
		group: 10,
		period: 4,
		block: "d",
		electronConfiguration: "[Ar] 3d⁸ 4s²",
		density: 8.912,
		meltingPoint: 1728,
		boilingPoint: 3186,
		discoveryYear: 1751,
	},
	{
		atomicNumber: 29,
		symbol: "Cu",
		name: "Copper",
		atomicMass: 63.546,
		category: "Transition Metal",
		group: 11,
		period: 4,
		block: "d",
		electronConfiguration: "[Ar] 3d¹⁰ 4s¹",
		density: 8.933,
		meltingPoint: 1357.77,
		boilingPoint: 2835,
		discoveryYear: null,
	},
	{
		atomicNumber: 30,
		symbol: "Zn",
		name: "Zinc",
		atomicMass: 65.38,
		category: "Transition Metal",
		group: 12,
		period: 4,
		block: "d",
		electronConfiguration: "[Ar] 3d¹⁰ 4s²",
		density: 7.134,
		meltingPoint: 692.88,
		boilingPoint: 1180,
		discoveryYear: null,
	},
	{
		atomicNumber: 31,
		symbol: "Ga",
		name: "Gallium",
		atomicMass: 69.723,
		category: "Post-Transition Metal",
		group: 13,
		period: 4,
		block: "p",
		electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p¹",
		density: 5.907,
		meltingPoint: 302.91,
		boilingPoint: 2477,
		discoveryYear: 1875,
	},
	{
		atomicNumber: 32,
		symbol: "Ge",
		name: "Germanium",
		atomicMass: 72.64,
		category: "Metalloid",
		group: 14,
		period: 4,
		block: "p",
		electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p²",
		density: 5.323,
		meltingPoint: 1211.4,
		boilingPoint: 3106,
		discoveryYear: 1886,
	},
	{
		atomicNumber: 33,
		symbol: "As",
		name: "Arsenic",
		atomicMass: 74.922,
		category: "Metalloid",
		group: 15,
		period: 4,
		block: "p",
		electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p³",
		density: 5.776,
		meltingPoint: 1090,
		boilingPoint: 887,
		discoveryYear: null,
	},
	{
		atomicNumber: 34,
		symbol: "Se",
		name: "Selenium",
		atomicMass: 78.96,
		category: "Nonmetal",
		group: 16,
		period: 4,
		block: "p",
		electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁴",
		density: 4.809,
		meltingPoint: 453,
		boilingPoint: 958,
		discoveryYear: 1817,
	},
	{
		atomicNumber: 35,
		symbol: "Br",
		name: "Bromine",
		atomicMass: 79.904,
		category: "Halogen",
		group: 17,
		period: 4,
		block: "p",
		electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁵",
		density: 3.122,
		meltingPoint: 265.8,
		boilingPoint: 332.0,
		discoveryYear: 1826,
	},
	{
		atomicNumber: 36,
		symbol: "Kr",
		name: "Krypton",
		atomicMass: 83.798,
		category: "Noble Gas",
		group: 18,
		period: 4,
		block: "p",
		electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁶",
		density: 0.003733,
		meltingPoint: 115.79,
		boilingPoint: 119.93,
		discoveryYear: 1898,
	},
	{
		atomicNumber: 37,
		symbol: "Rb",
		name: "Rubidium",
		atomicMass: 85.468,
		category: "Alkali Metal",
		group: 1,
		period: 5,
		block: "s",
		electronConfiguration: "[Kr] 5s¹",
		density: 1.532,
		meltingPoint: 312.46,
		boilingPoint: 961,
		discoveryYear: 1861,
	},
	{
		atomicNumber: 38,
		symbol: "Sr",
		name: "Strontium",
		atomicMass: 87.62,
		category: "Alkaline Earth Metal",
		group: 2,
		period: 5,
		block: "s",
		electronConfiguration: "[Kr] 5s²",
		density: 2.64,
		meltingPoint: 1050,
		boilingPoint: 1655,
		discoveryYear: 1790,
	},
	{
		atomicNumber: 39,
		symbol: "Y",
		name: "Yttrium",
		atomicMass: 88.906,
		category: "Transition Metal",
		group: 3,
		period: 5,
		block: "d",
		electronConfiguration: "[Kr] 4d¹ 5s²",
		density: 4.469,
		meltingPoint: 1799,
		boilingPoint: 3609,
		discoveryYear: 1794,
	},
	{
		atomicNumber: 40,
		symbol: "Zr",
		name: "Zirconium",
		atomicMass: 91.224,
		category: "Transition Metal",
		group: 4,
		period: 5,
		block: "d",
		electronConfiguration: "[Kr] 4d² 5s²",
		density: 6.506,
		meltingPoint: 2128,
		boilingPoint: 4682,
		discoveryYear: 1789,
	},
	{
		atomicNumber: 41,
		symbol: "Nb",
		name: "Niobium",
		atomicMass: 92.906,
		category: "Transition Metal",
		group: 5,
		period: 5,
		block: "d",
		electronConfiguration: "[Kr] 4d⁴ 5s¹",
		density: 8.57,
		meltingPoint: 2750,
		boilingPoint: 5017,
		discoveryYear: 1801,
	},
	{
		atomicNumber: 42,
		symbol: "Mo",
		name: "Molybdenum",
		atomicMass: 95.96,
		category: "Transition Metal",
		group: 6,
		period: 5,
		block: "d",
		electronConfiguration: "[Kr] 4d⁵ 5s¹",
		density: 10.22,
		meltingPoint: 2896,
		boilingPoint: 4912,
		discoveryYear: 1778,
	},
	{
		atomicNumber: 43,
		symbol: "Tc",
		name: "Technetium",
		atomicMass: 98,
		category: "Transition Metal",
		group: 7,
		period: 5,
		block: "d",
		electronConfiguration: "[Kr] 4d⁵ 5s²",
		density: 11.5,
		meltingPoint: 2430,
		boilingPoint: 4538,
		discoveryYear: 1937,
	},
	{
		atomicNumber: 44,
		symbol: "Ru",
		name: "Ruthenium",
		atomicMass: 101.07,
		category: "Transition Metal",
		group: 8,
		period: 5,
		block: "d",
		electronConfiguration: "[Kr] 4d⁷ 5s¹",
		density: 12.37,
		meltingPoint: 2607,
		boilingPoint: 4423,
		discoveryYear: 1844,
	},
	{
		atomicNumber: 45,
		symbol: "Rh",
		name: "Rhodium",
		atomicMass: 102.91,
		category: "Transition Metal",
		group: 9,
		period: 5,
		block: "d",
		electronConfiguration: "[Kr] 4d⁸ 5s¹",
		density: 12.41,
		meltingPoint: 2237,
		boilingPoint: 3968,
		discoveryYear: 1803,
	},
	{
		atomicNumber: 46,
		symbol: "Pd",
		name: "Palladium",
		atomicMass: 106.42,
		category: "Transition Metal",
		group: 10,
		period: 5,
		block: "d",
		electronConfiguration: "[Kr] 4d¹⁰",
		density: 12.02,
		meltingPoint: 1828.05,
		boilingPoint: 3236,
		discoveryYear: 1803,
	},
	{
		atomicNumber: 47,
		symbol: "Ag",
		name: "Silver",
		atomicMass: 107.87,
		category: "Transition Metal",
		group: 11,
		period: 5,
		block: "d",
		electronConfiguration: "[Kr] 4d¹⁰ 5s¹",
		density: 10.501,
		meltingPoint: 1234.93,
		boilingPoint: 2435,
		discoveryYear: null,
	},
	{
		atomicNumber: 48,
		symbol: "Cd",
		name: "Cadmium",
		atomicMass: 112.41,
		category: "Transition Metal",
		group: 12,
		period: 5,
		block: "d",
		electronConfiguration: "[Kr] 4d¹⁰ 5s²",
		density: 8.69,
		meltingPoint: 594.22,
		boilingPoint: 1040,
		discoveryYear: 1817,
	},
	{
		atomicNumber: 49,
		symbol: "In",
		name: "Indium",
		atomicMass: 114.82,
		category: "Post-Transition Metal",
		group: 13,
		period: 5,
		block: "p",
		electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p¹",
		density: 7.31,
		meltingPoint: 429.75,
		boilingPoint: 2345,
		discoveryYear: 1863,
	},
	{
		atomicNumber: 50,
		symbol: "Sn",
		name: "Tin",
		atomicMass: 118.71,
		category: "Post-Transition Metal",
		group: 14,
		period: 5,
		block: "p",
		electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p²",
		density: 7.287,
		meltingPoint: 505.08,
		boilingPoint: 2875,
		discoveryYear: null,
	},
	{
		atomicNumber: 51,
		symbol: "Sb",
		name: "Antimony",
		atomicMass: 121.76,
		category: "Metalloid",
		group: 15,
		period: 5,
		block: "p",
		electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p³",
		density: 6.685,
		meltingPoint: 903.78,
		boilingPoint: 1860,
		discoveryYear: null,
	},
	{
		atomicNumber: 52,
		symbol: "Te",
		name: "Tellurium",
		atomicMass: 127.6,
		category: "Metalloid",
		group: 16,
		period: 5,
		block: "p",
		electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁴",
		density: 6.232,
		meltingPoint: 722.66,
		boilingPoint: 1261,
		discoveryYear: 1783,
	},
	{
		atomicNumber: 53,
		symbol: "I",
		name: "Iodine",
		atomicMass: 126.9,
		category: "Halogen",
		group: 17,
		period: 5,
		block: "p",
		electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁵",
		density: 4.93,
		meltingPoint: 386.85,
		boilingPoint: 457.4,
		discoveryYear: 1811,
	},
	{
		atomicNumber: 54,
		symbol: "Xe",
		name: "Xenon",
		atomicMass: 131.29,
		category: "Noble Gas",
		group: 18,
		period: 5,
		block: "p",
		electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁶",
		density: 0.005887,
		meltingPoint: 161.4,
		boilingPoint: 165.03,
		discoveryYear: 1898,
	},
	{
		atomicNumber: 55,
		symbol: "Cs",
		name: "Cesium",
		atomicMass: 132.91,
		category: "Alkali Metal",
		group: 1,
		period: 6,
		block: "s",
		electronConfiguration: "[Xe] 6s¹",
		density: 1.873,
		meltingPoint: 301.59,
		boilingPoint: 944,
		discoveryYear: 1860,
	},
	{
		atomicNumber: 56,
		symbol: "Ba",
		name: "Barium",
		atomicMass: 137.33,
		category: "Alkaline Earth Metal",
		group: 2,
		period: 6,
		block: "s",
		electronConfiguration: "[Xe] 6s²",
		density: 3.594,
		meltingPoint: 1000,
		boilingPoint: 2170,
		discoveryYear: 1808,
	},
	{
		atomicNumber: 57,
		symbol: "La",
		name: "Lanthanum",
		atomicMass: 138.91,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 5d¹ 6s²",
		density: 6.145,
		meltingPoint: 1193,
		boilingPoint: 3737,
		discoveryYear: 1839,
	},
	{
		atomicNumber: 58,
		symbol: "Ce",
		name: "Cerium",
		atomicMass: 140.12,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 4f¹ 5d¹ 6s²",
		density: 6.77,
		meltingPoint: 1068,
		boilingPoint: 3716,
		discoveryYear: 1803,
	},
	{
		atomicNumber: 59,
		symbol: "Pr",
		name: "Praseodymium",
		atomicMass: 140.91,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 4f³ 6s²",
		density: 6.773,
		meltingPoint: 1208,
		boilingPoint: 3793,
		discoveryYear: 1885,
	},
	{
		atomicNumber: 60,
		symbol: "Nd",
		name: "Neodymium",
		atomicMass: 144.24,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 4f⁴ 6s²",
		density: 7.007,
		meltingPoint: 1297,
		boilingPoint: 3347,
		discoveryYear: 1885,
	},
	{
		atomicNumber: 61,
		symbol: "Pm",
		name: "Promethium",
		atomicMass: 145,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 4f⁵ 6s²",
		density: 7.26,
		meltingPoint: 1315,
		boilingPoint: 3273,
		discoveryYear: 1945,
	},
	{
		atomicNumber: 62,
		symbol: "Sm",
		name: "Samarium",
		atomicMass: 150.36,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 4f⁶ 6s²",
		density: 7.52,
		meltingPoint: 1345,
		boilingPoint: 2067,
		discoveryYear: 1879,
	},
	{
		atomicNumber: 63,
		symbol: "Eu",
		name: "Europium",
		atomicMass: 151.96,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 4f⁷ 6s²",
		density: 5.243,
		meltingPoint: 1099,
		boilingPoint: 1802,
		discoveryYear: 1901,
	},
	{
		atomicNumber: 64,
		symbol: "Gd",
		name: "Gadolinium",
		atomicMass: 157.25,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 4f⁷ 5d¹ 6s²",
		density: 7.895,
		meltingPoint: 1585,
		boilingPoint: 3546,
		discoveryYear: 1880,
	},
	{
		atomicNumber: 65,
		symbol: "Tb",
		name: "Terbium",
		atomicMass: 158.93,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 4f⁹ 6s²",
		density: 8.229,
		meltingPoint: 1629,
		boilingPoint: 3503,
		discoveryYear: 1843,
	},
	{
		atomicNumber: 66,
		symbol: "Dy",
		name: "Dysprosium",
		atomicMass: 162.5,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 4f¹⁰ 6s²",
		density: 8.55,
		meltingPoint: 1680,
		boilingPoint: 2840,
		discoveryYear: 1886,
	},
	{
		atomicNumber: 67,
		symbol: "Ho",
		name: "Holmium",
		atomicMass: 164.93,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 4f¹¹ 6s²",
		density: 8.795,
		meltingPoint: 1734,
		boilingPoint: 2993,
		discoveryYear: 1878,
	},
	{
		atomicNumber: 68,
		symbol: "Er",
		name: "Erbium",
		atomicMass: 167.26,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 4f¹² 6s²",
		density: 9.066,
		meltingPoint: 1802,
		boilingPoint: 3141,
		discoveryYear: 1843,
	},
	{
		atomicNumber: 69,
		symbol: "Tm",
		name: "Thulium",
		atomicMass: 168.93,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 4f¹³ 6s²",
		density: 9.321,
		meltingPoint: 1818,
		boilingPoint: 2223,
		discoveryYear: 1879,
	},
	{
		atomicNumber: 70,
		symbol: "Yb",
		name: "Ytterbium",
		atomicMass: 173.05,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "f",
		electronConfiguration: "[Xe] 4f¹⁴ 6s²",
		density: 6.965,
		meltingPoint: 1097,
		boilingPoint: 1469,
		discoveryYear: 1878,
	},
	{
		atomicNumber: 71,
		symbol: "Lu",
		name: "Lutetium",
		atomicMass: 174.97,
		category: "Lanthanide",
		group: null,
		period: 6,
		block: "d",
		electronConfiguration: "[Xe] 4f¹⁴ 5d¹ 6s²",
		density: 9.84,
		meltingPoint: 1925,
		boilingPoint: 3675,
		discoveryYear: 1907,
	},
	{
		atomicNumber: 72,
		symbol: "Hf",
		name: "Hafnium",
		atomicMass: 178.49,
		category: "Transition Metal",
		group: 4,
		period: 6,
		block: "d",
		electronConfiguration: "[Xe] 4f¹⁴ 5d² 6s²",
		density: 13.31,
		meltingPoint: 2506,
		boilingPoint: 4876,
		discoveryYear: 1923,
	},
	{
		atomicNumber: 73,
		symbol: "Ta",
		name: "Tantalum",
		atomicMass: 180.95,
		category: "Transition Metal",
		group: 5,
		period: 6,
		block: "d",
		electronConfiguration: "[Xe] 4f¹⁴ 5d³ 6s²",
		density: 16.654,
		meltingPoint: 3290,
		boilingPoint: 5731,
		discoveryYear: 1802,
	},
	{
		atomicNumber: 74,
		symbol: "W",
		name: "Tungsten",
		atomicMass: 183.84,
		category: "Transition Metal",
		group: 6,
		period: 6,
		block: "d",
		electronConfiguration: "[Xe] 4f¹⁴ 5d⁴ 6s²",
		density: 19.25,
		meltingPoint: 3695,
		boilingPoint: 5828,
		discoveryYear: 1783,
	},
	{
		atomicNumber: 75,
		symbol: "Re",
		name: "Rhenium",
		atomicMass: 186.21,
		category: "Transition Metal",
		group: 7,
		period: 6,
		block: "d",
		electronConfiguration: "[Xe] 4f¹⁴ 5d⁵ 6s²",
		density: 21.02,
		meltingPoint: 3459,
		boilingPoint: 5869,
		discoveryYear: 1925,
	},
	{
		atomicNumber: 76,
		symbol: "Os",
		name: "Osmium",
		atomicMass: 190.23,
		category: "Transition Metal",
		group: 8,
		period: 6,
		block: "d",
		electronConfiguration: "[Xe] 4f¹⁴ 5d⁶ 6s²",
		density: 22.61,
		meltingPoint: 3306,
		boilingPoint: 5285,
		discoveryYear: 1803,
	},
	{
		atomicNumber: 77,
		symbol: "Ir",
		name: "Iridium",
		atomicMass: 192.22,
		category: "Transition Metal",
		group: 9,
		period: 6,
		block: "d",
		electronConfiguration: "[Xe] 4f¹⁴ 5d⁷ 6s²",
		density: 22.56,
		meltingPoint: 2719,
		boilingPoint: 4701,
		discoveryYear: 1803,
	},
	{
		atomicNumber: 78,
		symbol: "Pt",
		name: "Platinum",
		atomicMass: 195.08,
		category: "Transition Metal",
		group: 10,
		period: 6,
		block: "d",
		electronConfiguration: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
		density: 21.46,
		meltingPoint: 2041.4,
		boilingPoint: 4098,
		discoveryYear: 1735,
	},
	{
		atomicNumber: 79,
		symbol: "Au",
		name: "Gold",
		atomicMass: 196.97,
		category: "Transition Metal",
		group: 11,
		period: 6,
		block: "d",
		electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
		density: 19.282,
		meltingPoint: 1337.33,
		boilingPoint: 3129,
		discoveryYear: null,
	},
	{
		atomicNumber: 80,
		symbol: "Hg",
		name: "Mercury",
		atomicMass: 200.59,
		category: "Transition Metal",
		group: 12,
		period: 6,
		block: "d",
		electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
		density: 13.5336,
		meltingPoint: 234.43,
		boilingPoint: 629.88,
		discoveryYear: null,
	},
	{
		atomicNumber: 81,
		symbol: "Tl",
		name: "Thallium",
		atomicMass: 204.38,
		category: "Post-Transition Metal",
		group: 13,
		period: 6,
		block: "p",
		electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
		density: 11.85,
		meltingPoint: 577,
		boilingPoint: 1746,
		discoveryYear: 1861,
	},
	{
		atomicNumber: 82,
		symbol: "Pb",
		name: "Lead",
		atomicMass: 207.2,
		category: "Post-Transition Metal",
		group: 14,
		period: 6,
		block: "p",
		electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
		density: 11.342,
		meltingPoint: 600.61,
		boilingPoint: 2022,
		discoveryYear: null,
	},
	{
		atomicNumber: 83,
		symbol: "Bi",
		name: "Bismuth",
		atomicMass: 208.98,
		category: "Post-Transition Metal",
		group: 15,
		period: 6,
		block: "p",
		electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
		density: 9.807,
		meltingPoint: 544.7,
		boilingPoint: 1837,
		discoveryYear: null,
	},
	{
		atomicNumber: 84,
		symbol: "Po",
		name: "Polonium",
		atomicMass: 209,
		category: "Metalloid",
		group: 16,
		period: 6,
		block: "p",
		electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
		density: 9.32,
		meltingPoint: 527,
		boilingPoint: 1235,
		discoveryYear: 1898,
	},
	{
		atomicNumber: 85,
		symbol: "At",
		name: "Astatine",
		atomicMass: 210,
		category: "Halogen",
		group: 17,
		period: 6,
		block: "p",
		electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
		density: 7,
		meltingPoint: 575,
		boilingPoint: 610,
		discoveryYear: 1940,
	},
	{
		atomicNumber: 86,
		symbol: "Rn",
		name: "Radon",
		atomicMass: 222,
		category: "Noble Gas",
		group: 18,
		period: 6,
		block: "p",
		electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
		density: 0.00973,
		meltingPoint: 202,
		boilingPoint: 211.3,
		discoveryYear: 1900,
	},
	{
		atomicNumber: 87,
		symbol: "Fr",
		name: "Francium",
		atomicMass: 223,
		category: "Alkali Metal",
		group: 1,
		period: 7,
		block: "s",
		electronConfiguration: "[Rn] 7s¹",
		density: 1.87,
		meltingPoint: 300,
		boilingPoint: 950,
		discoveryYear: 1939,
	},
	{
		atomicNumber: 88,
		symbol: "Ra",
		name: "Radium",
		atomicMass: 226,
		category: "Alkaline Earth Metal",
		group: 2,
		period: 7,
		block: "s",
		electronConfiguration: "[Rn] 7s²",
		density: 5.5,
		meltingPoint: 973,
		boilingPoint: 2010,
		discoveryYear: 1898,
	},
	{
		atomicNumber: 89,
		symbol: "Ac",
		name: "Actinium",
		atomicMass: 227,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 6d¹ 7s²",
		density: 10.07,
		meltingPoint: 1323,
		boilingPoint: 3471,
		discoveryYear: 1899,
	},
	{
		atomicNumber: 90,
		symbol: "Th",
		name: "Thorium",
		atomicMass: 232.04,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 6d² 7s²",
		density: 11.72,
		meltingPoint: 2115,
		boilingPoint: 5061,
		discoveryYear: 1829,
	},
	{
		atomicNumber: 91,
		symbol: "Pa",
		name: "Protactinium",
		atomicMass: 231.04,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 5f² 6d¹ 7s²",
		density: 15.37,
		meltingPoint: 1841,
		boilingPoint: 4300,
		discoveryYear: 1913,
	},
	{
		atomicNumber: 92,
		symbol: "U",
		name: "Uranium",
		atomicMass: 238.03,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 5f³ 6d¹ 7s²",
		density: 18.95,
		meltingPoint: 1405.3,
		boilingPoint: 4404,
		discoveryYear: 1789,
	},
	{
		atomicNumber: 93,
		symbol: "Np",
		name: "Neptunium",
		atomicMass: 237,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 5f⁴ 6d¹ 7s²",
		density: 20.45,
		meltingPoint: 912,
		boilingPoint: 4447,
		discoveryYear: 1940,
	},
	{
		atomicNumber: 94,
		symbol: "Pu",
		name: "Plutonium",
		atomicMass: 244,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 5f⁶ 7s²",
		density: 19.84,
		meltingPoint: 912.5,
		boilingPoint: 3505,
		discoveryYear: 1940,
	},
	{
		atomicNumber: 95,
		symbol: "Am",
		name: "Americium",
		atomicMass: 243,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 5f⁷ 7s²",
		density: 13.69,
		meltingPoint: 1449,
		boilingPoint: 2880,
		discoveryYear: 1944,
	},
	{
		atomicNumber: 96,
		symbol: "Cm",
		name: "Curium",
		atomicMass: 247,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 5f⁷ 6d¹ 7s²",
		density: 13.51,
		meltingPoint: 1613,
		boilingPoint: 3383,
		discoveryYear: 1944,
	},
	{
		atomicNumber: 97,
		symbol: "Bk",
		name: "Berkelium",
		atomicMass: 247,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 5f⁹ 7s²",
		density: 14.79,
		meltingPoint: 1259,
		boilingPoint: 2900,
		discoveryYear: 1949,
	},
	{
		atomicNumber: 98,
		symbol: "Cf",
		name: "Californium",
		atomicMass: 251,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 5f¹⁰ 7s²",
		density: 15.1,
		meltingPoint: 1173,
		boilingPoint: 1743,
		discoveryYear: 1950,
	},
	{
		atomicNumber: 99,
		symbol: "Es",
		name: "Einsteinium",
		atomicMass: 252,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 5f¹¹ 7s²",
		density: 8.84,
		meltingPoint: 1133,
		boilingPoint: 1269,
		discoveryYear: 1952,
	},
	{
		atomicNumber: 100,
		symbol: "Fm",
		name: "Fermium",
		atomicMass: 257,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 5f¹² 7s²",
		density: null,
		meltingPoint: 1800,
		boilingPoint: null,
		discoveryYear: 1952,
	},
	{
		atomicNumber: 101,
		symbol: "Md",
		name: "Mendelevium",
		atomicMass: 258,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 5f¹³ 7s²",
		density: null,
		meltingPoint: 1100,
		boilingPoint: null,
		discoveryYear: 1955,
	},
	{
		atomicNumber: 102,
		symbol: "No",
		name: "Nobelium",
		atomicMass: 259,
		category: "Actinide",
		group: null,
		period: 7,
		block: "f",
		electronConfiguration: "[Rn] 5f¹⁴ 7s²",
		density: null,
		meltingPoint: 1100,
		boilingPoint: null,
		discoveryYear: 1958,
	},
	{
		atomicNumber: 103,
		symbol: "Lr",
		name: "Lawrencium",
		atomicMass: 266,
		category: "Actinide",
		group: null,
		period: 7,
		block: "d",
		electronConfiguration: "[Rn] 5f¹⁴ 7s² 7p¹",
		density: null,
		meltingPoint: 1900,
		boilingPoint: null,
		discoveryYear: 1961,
	},
	{
		atomicNumber: 104,
		symbol: "Rf",
		name: "Rutherfordium",
		atomicMass: 267,
		category: "Transition Metal",
		group: 4,
		period: 7,
		block: "d",
		electronConfiguration: "[Rn] 5f¹⁴ 6d² 7s²",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 1969,
	},
	{
		atomicNumber: 105,
		symbol: "Db",
		name: "Dubnium",
		atomicMass: 268,
		category: "Transition Metal",
		group: 5,
		period: 7,
		block: "d",
		electronConfiguration: "[Rn] 5f¹⁴ 6d³ 7s²",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 1970,
	},
	{
		atomicNumber: 106,
		symbol: "Sg",
		name: "Seaborgium",
		atomicMass: 269,
		category: "Transition Metal",
		group: 6,
		period: 7,
		block: "d",
		electronConfiguration: "[Rn] 5f¹⁴ 6d⁴ 7s²",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 1974,
	},
	{
		atomicNumber: 107,
		symbol: "Bh",
		name: "Bohrium",
		atomicMass: 270,
		category: "Transition Metal",
		group: 7,
		period: 7,
		block: "d",
		electronConfiguration: "[Rn] 5f¹⁴ 6d⁵ 7s²",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 1981,
	},
	{
		atomicNumber: 108,
		symbol: "Hs",
		name: "Hassium",
		atomicMass: 277,
		category: "Transition Metal",
		group: 8,
		period: 7,
		block: "d",
		electronConfiguration: "[Rn] 5f¹⁴ 6d⁶ 7s²",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 1984,
	},
	{
		atomicNumber: 109,
		symbol: "Mt",
		name: "Meitnerium",
		atomicMass: 278,
		category: "Transition Metal",
		group: 9,
		period: 7,
		block: "d",
		electronConfiguration: "[Rn] 5f¹⁴ 6d⁷ 7s²",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 1982,
	},
	{
		atomicNumber: 110,
		symbol: "Ds",
		name: "Darmstadtium",
		atomicMass: 281,
		category: "Transition Metal",
		group: 10,
		period: 7,
		block: "d",
		electronConfiguration: "[Rn] 5f¹⁴ 6d⁸ 7s²",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 1994,
	},
	{
		atomicNumber: 111,
		symbol: "Rg",
		name: "Roentgenium",
		atomicMass: 282,
		category: "Transition Metal",
		group: 11,
		period: 7,
		block: "d",
		electronConfiguration: "[Rn] 5f¹⁴ 6d⁹ 7s²",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 1994,
	},
	{
		atomicNumber: 112,
		symbol: "Cn",
		name: "Copernicium",
		atomicMass: 285,
		category: "Transition Metal",
		group: 12,
		period: 7,
		block: "d",
		electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 1996,
	},
	{
		atomicNumber: 113,
		symbol: "Nh",
		name: "Nihonium",
		atomicMass: 286,
		category: "Post-Transition Metal",
		group: 13,
		period: 7,
		block: "p",
		electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 2004,
	},
	{
		atomicNumber: 114,
		symbol: "Fl",
		name: "Flerovium",
		atomicMass: 289,
		category: "Post-Transition Metal",
		group: 14,
		period: 7,
		block: "p",
		electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 1999,
	},
	{
		atomicNumber: 115,
		symbol: "Mc",
		name: "Moscovium",
		atomicMass: 290,
		category: "Post-Transition Metal",
		group: 15,
		period: 7,
		block: "p",
		electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 2003,
	},
	{
		atomicNumber: 116,
		symbol: "Lv",
		name: "Livermorium",
		atomicMass: 293,
		category: "Post-Transition Metal",
		group: 16,
		period: 7,
		block: "p",
		electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 2000,
	},
	{
		atomicNumber: 117,
		symbol: "Ts",
		name: "Tennessine",
		atomicMass: 294,
		category: "Halogen",
		group: 17,
		period: 7,
		block: "p",
		electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 2010,
	},
	{
		atomicNumber: 118,
		symbol: "Og",
		name: "Oganesson",
		atomicMass: 294,
		category: "Noble Gas",
		group: 18,
		period: 7,
		block: "p",
		electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
		density: null,
		meltingPoint: null,
		boilingPoint: null,
		discoveryYear: 2006,
	},
];
