FROM oven/bun:1-alpine AS base

ENV NODE_ENV=production
WORKDIR /node

# =========================================================================== #
FROM base AS builder

COPY . .

RUN bun install -g turbo
RUN turbo prune backend --docker

# =========================================================================== #
FROM base AS installer

COPY --from=builder /node/out/json/ ./
RUN bun install
COPY --from=builder /node/out/full/ .

# =========================================================================== #
FROM base AS production

COPY --from=installer /node/apps/backend/ ./
COPY --from=installer /node/node_modules ./node_modules
COPY --from=installer /node/package.json ./package.json
COPY --from=installer /node/bun.lock ./bun.lock

RUN mkdir -p /node/logs /node/keys /node/uploads \
  && chmod 777 /node/logs /node/keys /node/uploads

EXPOSE 81

CMD ["sh", "-c", "bun run db:migrate && bun run db:seed && bun run start"]
