/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboardLayout'
import { Route as R403RouteImport } from './routes/403'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardLayoutUsersRouteImport } from './routes/_dashboardLayout/users'
import { Route as DashboardLayoutGraphAdminRouteImport } from './routes/_dashboardLayout/graph-admin'
import { Route as DashboardLayoutDevRouteImport } from './routes/_dashboardLayout/dev'
import { Route as DashboardLayoutRolesIndexRouteImport } from './routes/_dashboardLayout/roles/index'
import { Route as DashboardLayoutNotificationsIndexRouteImport } from './routes/_dashboardLayout/notifications/index'
import { Route as DashboardLayoutDashboardIndexRouteImport } from './routes/_dashboardLayout/dashboard/index'
import { Route as DashboardLayoutUsersCreateRouteImport } from './routes/_dashboardLayout/users/create'
import { Route as DashboardLayoutRolesCreateRouteImport } from './routes/_dashboardLayout/roles/create'
import { Route as DashboardLayoutPersonalNotificationsRouteImport } from './routes/_dashboardLayout/personal/notifications'
import { Route as DashboardLayoutUsersEditUserIdRouteImport } from './routes/_dashboardLayout/users/edit.$userId'
import { Route as DashboardLayoutUsersDetailUserIdRouteImport } from './routes/_dashboardLayout/users/detail.$userId'
import { Route as DashboardLayoutUsersDeleteUserIdRouteImport } from './routes/_dashboardLayout/users/delete.$userId'
import { Route as DashboardLayoutRolesViewRoleIdRouteImport } from './routes/_dashboardLayout/roles/view.$roleId'
import { Route as DashboardLayoutRolesEditRoleIdRouteImport } from './routes/_dashboardLayout/roles/edit.$roleId'

const IndexLazyRouteImport = createFileRoute('/')()
const LogoutIndexLazyRouteImport = createFileRoute('/logout/')()
const OauthMicrosoftCallbackLazyRouteImport = createFileRoute(
  '/oauth/microsoft-callback',
)()
const OauthMicrosoftAdminCallbackLazyRouteImport = createFileRoute(
  '/oauth/microsoft-admin-callback',
)()
const OauthGoogleCallbackLazyRouteImport = createFileRoute(
  '/oauth/google-callback',
)()
const DashboardLayoutAppSettingsIndexLazyRouteImport = createFileRoute(
  '/_dashboardLayout/app-settings/',
)()
const DashboardLayoutAppSettingsEditIdLazyRouteImport = createFileRoute(
  '/_dashboardLayout/app-settings/edit/$id',
)()

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const LogoutIndexLazyRoute = LogoutIndexLazyRouteImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/logout/index.lazy').then((d) => d.Route))
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))
const OauthMicrosoftCallbackLazyRoute =
  OauthMicrosoftCallbackLazyRouteImport.update({
    id: '/oauth/microsoft-callback',
    path: '/oauth/microsoft-callback',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/oauth/microsoft-callback.lazy').then((d) => d.Route),
  )
const OauthMicrosoftAdminCallbackLazyRoute =
  OauthMicrosoftAdminCallbackLazyRouteImport.update({
    id: '/oauth/microsoft-admin-callback',
    path: '/oauth/microsoft-admin-callback',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/oauth/microsoft-admin-callback.lazy').then((d) => d.Route),
  )
const OauthGoogleCallbackLazyRoute = OauthGoogleCallbackLazyRouteImport.update({
  id: '/oauth/google-callback',
  path: '/oauth/google-callback',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/oauth/google-callback.lazy').then((d) => d.Route),
)
const DashboardLayoutUsersRoute = DashboardLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardLayoutRoute,
} as any).lazy(() =>
  import('./routes/_dashboardLayout/users.lazy').then((d) => d.Route),
)
const DashboardLayoutGraphAdminRoute =
  DashboardLayoutGraphAdminRouteImport.update({
    id: '/graph-admin',
    path: '/graph-admin',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDevRoute = DashboardLayoutDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutAppSettingsIndexLazyRoute =
  DashboardLayoutAppSettingsIndexLazyRouteImport.update({
    id: '/app-settings/',
    path: '/app-settings/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_dashboardLayout/app-settings/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardLayoutRolesIndexRoute =
  DashboardLayoutRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_dashboardLayout/roles/index.lazy').then((d) => d.Route),
  )
const DashboardLayoutNotificationsIndexRoute =
  DashboardLayoutNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDashboardIndexRoute =
  DashboardLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutUsersCreateRoute =
  DashboardLayoutUsersCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardLayoutUsersRoute,
  } as any)
const DashboardLayoutRolesCreateRoute =
  DashboardLayoutRolesCreateRouteImport.update({
    id: '/roles/create',
    path: '/roles/create',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPersonalNotificationsRoute =
  DashboardLayoutPersonalNotificationsRouteImport.update({
    id: '/personal/notifications',
    path: '/personal/notifications',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutAppSettingsEditIdLazyRoute =
  DashboardLayoutAppSettingsEditIdLazyRouteImport.update({
    id: '/app-settings/edit/$id',
    path: '/app-settings/edit/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_dashboardLayout/app-settings/edit/$id.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardLayoutUsersEditUserIdRoute =
  DashboardLayoutUsersEditUserIdRouteImport.update({
    id: '/edit/$userId',
    path: '/edit/$userId',
    getParentRoute: () => DashboardLayoutUsersRoute,
  } as any)
const DashboardLayoutUsersDetailUserIdRoute =
  DashboardLayoutUsersDetailUserIdRouteImport.update({
    id: '/detail/$userId',
    path: '/detail/$userId',
    getParentRoute: () => DashboardLayoutUsersRoute,
  } as any)
const DashboardLayoutUsersDeleteUserIdRoute =
  DashboardLayoutUsersDeleteUserIdRouteImport.update({
    id: '/delete/$userId',
    path: '/delete/$userId',
    getParentRoute: () => DashboardLayoutUsersRoute,
  } as any)
const DashboardLayoutRolesViewRoleIdRoute =
  DashboardLayoutRolesViewRoleIdRouteImport.update({
    id: '/roles/view/$roleId',
    path: '/roles/view/$roleId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutRolesEditRoleIdRoute =
  DashboardLayoutRolesEditRoleIdRouteImport.update({
    id: '/roles/edit/$roleId',
    path: '/roles/edit/$roleId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/403': typeof R403Route
  '/dev': typeof DashboardLayoutDevRoute
  '/graph-admin': typeof DashboardLayoutGraphAdminRoute
  '/users': typeof DashboardLayoutUsersRouteWithChildren
  '/oauth/google-callback': typeof OauthGoogleCallbackLazyRoute
  '/oauth/microsoft-admin-callback': typeof OauthMicrosoftAdminCallbackLazyRoute
  '/oauth/microsoft-callback': typeof OauthMicrosoftCallbackLazyRoute
  '/login': typeof LoginIndexRoute
  '/logout': typeof LogoutIndexLazyRoute
  '/personal/notifications': typeof DashboardLayoutPersonalNotificationsRoute
  '/roles/create': typeof DashboardLayoutRolesCreateRoute
  '/users/create': typeof DashboardLayoutUsersCreateRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/notifications': typeof DashboardLayoutNotificationsIndexRoute
  '/roles': typeof DashboardLayoutRolesIndexRoute
  '/app-settings': typeof DashboardLayoutAppSettingsIndexLazyRoute
  '/roles/edit/$roleId': typeof DashboardLayoutRolesEditRoleIdRoute
  '/roles/view/$roleId': typeof DashboardLayoutRolesViewRoleIdRoute
  '/users/delete/$userId': typeof DashboardLayoutUsersDeleteUserIdRoute
  '/users/detail/$userId': typeof DashboardLayoutUsersDetailUserIdRoute
  '/users/edit/$userId': typeof DashboardLayoutUsersEditUserIdRoute
  '/app-settings/edit/$id': typeof DashboardLayoutAppSettingsEditIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/403': typeof R403Route
  '/dev': typeof DashboardLayoutDevRoute
  '/graph-admin': typeof DashboardLayoutGraphAdminRoute
  '/users': typeof DashboardLayoutUsersRouteWithChildren
  '/oauth/google-callback': typeof OauthGoogleCallbackLazyRoute
  '/oauth/microsoft-admin-callback': typeof OauthMicrosoftAdminCallbackLazyRoute
  '/oauth/microsoft-callback': typeof OauthMicrosoftCallbackLazyRoute
  '/login': typeof LoginIndexRoute
  '/logout': typeof LogoutIndexLazyRoute
  '/personal/notifications': typeof DashboardLayoutPersonalNotificationsRoute
  '/roles/create': typeof DashboardLayoutRolesCreateRoute
  '/users/create': typeof DashboardLayoutUsersCreateRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/notifications': typeof DashboardLayoutNotificationsIndexRoute
  '/roles': typeof DashboardLayoutRolesIndexRoute
  '/app-settings': typeof DashboardLayoutAppSettingsIndexLazyRoute
  '/roles/edit/$roleId': typeof DashboardLayoutRolesEditRoleIdRoute
  '/roles/view/$roleId': typeof DashboardLayoutRolesViewRoleIdRoute
  '/users/delete/$userId': typeof DashboardLayoutUsersDeleteUserIdRoute
  '/users/detail/$userId': typeof DashboardLayoutUsersDetailUserIdRoute
  '/users/edit/$userId': typeof DashboardLayoutUsersEditUserIdRoute
  '/app-settings/edit/$id': typeof DashboardLayoutAppSettingsEditIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/403': typeof R403Route
  '/_dashboardLayout': typeof DashboardLayoutRouteWithChildren
  '/_dashboardLayout/dev': typeof DashboardLayoutDevRoute
  '/_dashboardLayout/graph-admin': typeof DashboardLayoutGraphAdminRoute
  '/_dashboardLayout/users': typeof DashboardLayoutUsersRouteWithChildren
  '/oauth/google-callback': typeof OauthGoogleCallbackLazyRoute
  '/oauth/microsoft-admin-callback': typeof OauthMicrosoftAdminCallbackLazyRoute
  '/oauth/microsoft-callback': typeof OauthMicrosoftCallbackLazyRoute
  '/login/': typeof LoginIndexRoute
  '/logout/': typeof LogoutIndexLazyRoute
  '/_dashboardLayout/personal/notifications': typeof DashboardLayoutPersonalNotificationsRoute
  '/_dashboardLayout/roles/create': typeof DashboardLayoutRolesCreateRoute
  '/_dashboardLayout/users/create': typeof DashboardLayoutUsersCreateRoute
  '/_dashboardLayout/dashboard/': typeof DashboardLayoutDashboardIndexRoute
  '/_dashboardLayout/notifications/': typeof DashboardLayoutNotificationsIndexRoute
  '/_dashboardLayout/roles/': typeof DashboardLayoutRolesIndexRoute
  '/_dashboardLayout/app-settings/': typeof DashboardLayoutAppSettingsIndexLazyRoute
  '/_dashboardLayout/roles/edit/$roleId': typeof DashboardLayoutRolesEditRoleIdRoute
  '/_dashboardLayout/roles/view/$roleId': typeof DashboardLayoutRolesViewRoleIdRoute
  '/_dashboardLayout/users/delete/$userId': typeof DashboardLayoutUsersDeleteUserIdRoute
  '/_dashboardLayout/users/detail/$userId': typeof DashboardLayoutUsersDetailUserIdRoute
  '/_dashboardLayout/users/edit/$userId': typeof DashboardLayoutUsersEditUserIdRoute
  '/_dashboardLayout/app-settings/edit/$id': typeof DashboardLayoutAppSettingsEditIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/dev'
    | '/graph-admin'
    | '/users'
    | '/oauth/google-callback'
    | '/oauth/microsoft-admin-callback'
    | '/oauth/microsoft-callback'
    | '/login'
    | '/logout'
    | '/personal/notifications'
    | '/roles/create'
    | '/users/create'
    | '/dashboard'
    | '/notifications'
    | '/roles'
    | '/app-settings'
    | '/roles/edit/$roleId'
    | '/roles/view/$roleId'
    | '/users/delete/$userId'
    | '/users/detail/$userId'
    | '/users/edit/$userId'
    | '/app-settings/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/dev'
    | '/graph-admin'
    | '/users'
    | '/oauth/google-callback'
    | '/oauth/microsoft-admin-callback'
    | '/oauth/microsoft-callback'
    | '/login'
    | '/logout'
    | '/personal/notifications'
    | '/roles/create'
    | '/users/create'
    | '/dashboard'
    | '/notifications'
    | '/roles'
    | '/app-settings'
    | '/roles/edit/$roleId'
    | '/roles/view/$roleId'
    | '/users/delete/$userId'
    | '/users/detail/$userId'
    | '/users/edit/$userId'
    | '/app-settings/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_dashboardLayout'
    | '/_dashboardLayout/dev'
    | '/_dashboardLayout/graph-admin'
    | '/_dashboardLayout/users'
    | '/oauth/google-callback'
    | '/oauth/microsoft-admin-callback'
    | '/oauth/microsoft-callback'
    | '/login/'
    | '/logout/'
    | '/_dashboardLayout/personal/notifications'
    | '/_dashboardLayout/roles/create'
    | '/_dashboardLayout/users/create'
    | '/_dashboardLayout/dashboard/'
    | '/_dashboardLayout/notifications/'
    | '/_dashboardLayout/roles/'
    | '/_dashboardLayout/app-settings/'
    | '/_dashboardLayout/roles/edit/$roleId'
    | '/_dashboardLayout/roles/view/$roleId'
    | '/_dashboardLayout/users/delete/$userId'
    | '/_dashboardLayout/users/detail/$userId'
    | '/_dashboardLayout/users/edit/$userId'
    | '/_dashboardLayout/app-settings/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  R403Route: typeof R403Route
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  OauthGoogleCallbackLazyRoute: typeof OauthGoogleCallbackLazyRoute
  OauthMicrosoftAdminCallbackLazyRoute: typeof OauthMicrosoftAdminCallbackLazyRoute
  OauthMicrosoftCallbackLazyRoute: typeof OauthMicrosoftCallbackLazyRoute
  LoginIndexRoute: typeof LoginIndexRoute
  LogoutIndexLazyRoute: typeof LogoutIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/microsoft-callback': {
      id: '/oauth/microsoft-callback'
      path: '/oauth/microsoft-callback'
      fullPath: '/oauth/microsoft-callback'
      preLoaderRoute: typeof OauthMicrosoftCallbackLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/microsoft-admin-callback': {
      id: '/oauth/microsoft-admin-callback'
      path: '/oauth/microsoft-admin-callback'
      fullPath: '/oauth/microsoft-admin-callback'
      preLoaderRoute: typeof OauthMicrosoftAdminCallbackLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google-callback': {
      id: '/oauth/google-callback'
      path: '/oauth/google-callback'
      fullPath: '/oauth/google-callback'
      preLoaderRoute: typeof OauthGoogleCallbackLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/users': {
      id: '/_dashboardLayout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardLayoutUsersRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/graph-admin': {
      id: '/_dashboardLayout/graph-admin'
      path: '/graph-admin'
      fullPath: '/graph-admin'
      preLoaderRoute: typeof DashboardLayoutGraphAdminRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/dev': {
      id: '/_dashboardLayout/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DashboardLayoutDevRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/app-settings/': {
      id: '/_dashboardLayout/app-settings/'
      path: '/app-settings'
      fullPath: '/app-settings'
      preLoaderRoute: typeof DashboardLayoutAppSettingsIndexLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/roles/': {
      id: '/_dashboardLayout/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof DashboardLayoutRolesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/notifications/': {
      id: '/_dashboardLayout/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof DashboardLayoutNotificationsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/dashboard/': {
      id: '/_dashboardLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/users/create': {
      id: '/_dashboardLayout/users/create'
      path: '/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof DashboardLayoutUsersCreateRouteImport
      parentRoute: typeof DashboardLayoutUsersRoute
    }
    '/_dashboardLayout/roles/create': {
      id: '/_dashboardLayout/roles/create'
      path: '/roles/create'
      fullPath: '/roles/create'
      preLoaderRoute: typeof DashboardLayoutRolesCreateRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/personal/notifications': {
      id: '/_dashboardLayout/personal/notifications'
      path: '/personal/notifications'
      fullPath: '/personal/notifications'
      preLoaderRoute: typeof DashboardLayoutPersonalNotificationsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/app-settings/edit/$id': {
      id: '/_dashboardLayout/app-settings/edit/$id'
      path: '/app-settings/edit/$id'
      fullPath: '/app-settings/edit/$id'
      preLoaderRoute: typeof DashboardLayoutAppSettingsEditIdLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/users/edit/$userId': {
      id: '/_dashboardLayout/users/edit/$userId'
      path: '/edit/$userId'
      fullPath: '/users/edit/$userId'
      preLoaderRoute: typeof DashboardLayoutUsersEditUserIdRouteImport
      parentRoute: typeof DashboardLayoutUsersRoute
    }
    '/_dashboardLayout/users/detail/$userId': {
      id: '/_dashboardLayout/users/detail/$userId'
      path: '/detail/$userId'
      fullPath: '/users/detail/$userId'
      preLoaderRoute: typeof DashboardLayoutUsersDetailUserIdRouteImport
      parentRoute: typeof DashboardLayoutUsersRoute
    }
    '/_dashboardLayout/users/delete/$userId': {
      id: '/_dashboardLayout/users/delete/$userId'
      path: '/delete/$userId'
      fullPath: '/users/delete/$userId'
      preLoaderRoute: typeof DashboardLayoutUsersDeleteUserIdRouteImport
      parentRoute: typeof DashboardLayoutUsersRoute
    }
    '/_dashboardLayout/roles/view/$roleId': {
      id: '/_dashboardLayout/roles/view/$roleId'
      path: '/roles/view/$roleId'
      fullPath: '/roles/view/$roleId'
      preLoaderRoute: typeof DashboardLayoutRolesViewRoleIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/roles/edit/$roleId': {
      id: '/_dashboardLayout/roles/edit/$roleId'
      path: '/roles/edit/$roleId'
      fullPath: '/roles/edit/$roleId'
      preLoaderRoute: typeof DashboardLayoutRolesEditRoleIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutUsersRouteChildren {
  DashboardLayoutUsersCreateRoute: typeof DashboardLayoutUsersCreateRoute
  DashboardLayoutUsersDeleteUserIdRoute: typeof DashboardLayoutUsersDeleteUserIdRoute
  DashboardLayoutUsersDetailUserIdRoute: typeof DashboardLayoutUsersDetailUserIdRoute
  DashboardLayoutUsersEditUserIdRoute: typeof DashboardLayoutUsersEditUserIdRoute
}

const DashboardLayoutUsersRouteChildren: DashboardLayoutUsersRouteChildren = {
  DashboardLayoutUsersCreateRoute: DashboardLayoutUsersCreateRoute,
  DashboardLayoutUsersDeleteUserIdRoute: DashboardLayoutUsersDeleteUserIdRoute,
  DashboardLayoutUsersDetailUserIdRoute: DashboardLayoutUsersDetailUserIdRoute,
  DashboardLayoutUsersEditUserIdRoute: DashboardLayoutUsersEditUserIdRoute,
}

const DashboardLayoutUsersRouteWithChildren =
  DashboardLayoutUsersRoute._addFileChildren(DashboardLayoutUsersRouteChildren)

interface DashboardLayoutRouteChildren {
  DashboardLayoutDevRoute: typeof DashboardLayoutDevRoute
  DashboardLayoutGraphAdminRoute: typeof DashboardLayoutGraphAdminRoute
  DashboardLayoutUsersRoute: typeof DashboardLayoutUsersRouteWithChildren
  DashboardLayoutPersonalNotificationsRoute: typeof DashboardLayoutPersonalNotificationsRoute
  DashboardLayoutRolesCreateRoute: typeof DashboardLayoutRolesCreateRoute
  DashboardLayoutDashboardIndexRoute: typeof DashboardLayoutDashboardIndexRoute
  DashboardLayoutNotificationsIndexRoute: typeof DashboardLayoutNotificationsIndexRoute
  DashboardLayoutRolesIndexRoute: typeof DashboardLayoutRolesIndexRoute
  DashboardLayoutAppSettingsIndexLazyRoute: typeof DashboardLayoutAppSettingsIndexLazyRoute
  DashboardLayoutRolesEditRoleIdRoute: typeof DashboardLayoutRolesEditRoleIdRoute
  DashboardLayoutRolesViewRoleIdRoute: typeof DashboardLayoutRolesViewRoleIdRoute
  DashboardLayoutAppSettingsEditIdLazyRoute: typeof DashboardLayoutAppSettingsEditIdLazyRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutDevRoute: DashboardLayoutDevRoute,
  DashboardLayoutGraphAdminRoute: DashboardLayoutGraphAdminRoute,
  DashboardLayoutUsersRoute: DashboardLayoutUsersRouteWithChildren,
  DashboardLayoutPersonalNotificationsRoute:
    DashboardLayoutPersonalNotificationsRoute,
  DashboardLayoutRolesCreateRoute: DashboardLayoutRolesCreateRoute,
  DashboardLayoutDashboardIndexRoute: DashboardLayoutDashboardIndexRoute,
  DashboardLayoutNotificationsIndexRoute:
    DashboardLayoutNotificationsIndexRoute,
  DashboardLayoutRolesIndexRoute: DashboardLayoutRolesIndexRoute,
  DashboardLayoutAppSettingsIndexLazyRoute:
    DashboardLayoutAppSettingsIndexLazyRoute,
  DashboardLayoutRolesEditRoleIdRoute: DashboardLayoutRolesEditRoleIdRoute,
  DashboardLayoutRolesViewRoleIdRoute: DashboardLayoutRolesViewRoleIdRoute,
  DashboardLayoutAppSettingsEditIdLazyRoute:
    DashboardLayoutAppSettingsEditIdLazyRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  R403Route: R403Route,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  OauthGoogleCallbackLazyRoute: OauthGoogleCallbackLazyRoute,
  OauthMicrosoftAdminCallbackLazyRoute: OauthMicrosoftAdminCallbackLazyRoute,
  OauthMicrosoftCallbackLazyRoute: OauthMicrosoftCallbackLazyRoute,
  LoginIndexRoute: LoginIndexRoute,
  LogoutIndexLazyRoute: LogoutIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
