/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardLayoutImport } from './routes/_dashboardLayout'
import { Route as R403Import } from './routes/403'
import { Route as DashboardLayoutUsersImport } from './routes/_dashboardLayout/users'
import { Route as DashboardLayoutRolesImport } from './routes/_dashboardLayout/roles'
import { Route as DashboardLayoutDevImport } from './routes/_dashboardLayout/dev'
import { Route as DashboardLayoutTimetableIndexImport } from './routes/_dashboardLayout/timetable/index'
import { Route as DashboardLayoutDashboardIndexImport } from './routes/_dashboardLayout/dashboard/index'
import { Route as DashboardLayoutUsersCreateImport } from './routes/_dashboardLayout/users/create'
import { Route as DashboardLayoutRolesCreateImport } from './routes/_dashboardLayout/roles/create'
import { Route as DashboardLayoutDevMultiSelectImport } from './routes/_dashboardLayout/dev/multi-select'
import { Route as DashboardLayoutDevCreateImport } from './routes/_dashboardLayout/dev/create'
import { Route as DashboardLayoutUsersEditUserIdImport } from './routes/_dashboardLayout/users/edit.$userId'
import { Route as DashboardLayoutUsersDetailUserIdImport } from './routes/_dashboardLayout/users/detail.$userId'
import { Route as DashboardLayoutUsersDeleteUserIdImport } from './routes/_dashboardLayout/users/delete.$userId'
import { Route as DashboardLayoutDevEditIdImport } from './routes/_dashboardLayout/dev/edit.$id'
import { Route as DashboardLayoutDevDetailIdImport } from './routes/_dashboardLayout/dev/detail.$id'
import { Route as DashboardLayoutDevDeleteIdImport } from './routes/_dashboardLayout/dev/delete.$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const LogoutIndexLazyImport = createFileRoute('/logout/')()
const LoginIndexLazyImport = createFileRoute('/login/')()

// Create/Update Routes

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRoute,
} as any)

const R403Route = R403Import.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LogoutIndexLazyRoute = LogoutIndexLazyImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logout/index.lazy').then((d) => d.Route))

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const DashboardLayoutUsersRoute = DashboardLayoutUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardLayoutRoute,
} as any).lazy(() =>
  import('./routes/_dashboardLayout/users.lazy').then((d) => d.Route),
)

const DashboardLayoutRolesRoute = DashboardLayoutRolesImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutDevRoute = DashboardLayoutDevImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutTimetableIndexRoute =
  DashboardLayoutTimetableIndexImport.update({
    id: '/timetable/',
    path: '/timetable/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDashboardIndexRoute =
  DashboardLayoutDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutUsersCreateRoute = DashboardLayoutUsersCreateImport.update(
  {
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardLayoutUsersRoute,
  } as any,
)

const DashboardLayoutRolesCreateRoute = DashboardLayoutRolesCreateImport.update(
  {
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardLayoutRolesRoute,
  } as any,
)

const DashboardLayoutDevMultiSelectRoute =
  DashboardLayoutDevMultiSelectImport.update({
    id: '/multi-select',
    path: '/multi-select',
    getParentRoute: () => DashboardLayoutDevRoute,
  } as any)

const DashboardLayoutDevCreateRoute = DashboardLayoutDevCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardLayoutDevRoute,
} as any)

const DashboardLayoutUsersEditUserIdRoute =
  DashboardLayoutUsersEditUserIdImport.update({
    id: '/edit/$userId',
    path: '/edit/$userId',
    getParentRoute: () => DashboardLayoutUsersRoute,
  } as any)

const DashboardLayoutUsersDetailUserIdRoute =
  DashboardLayoutUsersDetailUserIdImport.update({
    id: '/detail/$userId',
    path: '/detail/$userId',
    getParentRoute: () => DashboardLayoutUsersRoute,
  } as any)

const DashboardLayoutUsersDeleteUserIdRoute =
  DashboardLayoutUsersDeleteUserIdImport.update({
    id: '/delete/$userId',
    path: '/delete/$userId',
    getParentRoute: () => DashboardLayoutUsersRoute,
  } as any)

const DashboardLayoutDevEditIdRoute = DashboardLayoutDevEditIdImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => DashboardLayoutDevRoute,
} as any)

const DashboardLayoutDevDetailIdRoute = DashboardLayoutDevDetailIdImport.update(
  {
    id: '/detail/$id',
    path: '/detail/$id',
    getParentRoute: () => DashboardLayoutDevRoute,
  } as any,
)

const DashboardLayoutDevDeleteIdRoute = DashboardLayoutDevDeleteIdImport.update(
  {
    id: '/delete/$id',
    path: '/delete/$id',
    getParentRoute: () => DashboardLayoutDevRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403Import
      parentRoute: typeof rootRoute
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_dashboardLayout/dev': {
      id: '/_dashboardLayout/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DashboardLayoutDevImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/roles': {
      id: '/_dashboardLayout/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof DashboardLayoutRolesImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/users': {
      id: '/_dashboardLayout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardLayoutUsersImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_dashboardLayout/dev/create': {
      id: '/_dashboardLayout/dev/create'
      path: '/create'
      fullPath: '/dev/create'
      preLoaderRoute: typeof DashboardLayoutDevCreateImport
      parentRoute: typeof DashboardLayoutDevImport
    }
    '/_dashboardLayout/dev/multi-select': {
      id: '/_dashboardLayout/dev/multi-select'
      path: '/multi-select'
      fullPath: '/dev/multi-select'
      preLoaderRoute: typeof DashboardLayoutDevMultiSelectImport
      parentRoute: typeof DashboardLayoutDevImport
    }
    '/_dashboardLayout/roles/create': {
      id: '/_dashboardLayout/roles/create'
      path: '/create'
      fullPath: '/roles/create'
      preLoaderRoute: typeof DashboardLayoutRolesCreateImport
      parentRoute: typeof DashboardLayoutRolesImport
    }
    '/_dashboardLayout/users/create': {
      id: '/_dashboardLayout/users/create'
      path: '/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof DashboardLayoutUsersCreateImport
      parentRoute: typeof DashboardLayoutUsersImport
    }
    '/_dashboardLayout/dashboard/': {
      id: '/_dashboardLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/timetable/': {
      id: '/_dashboardLayout/timetable/'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof DashboardLayoutTimetableIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/dev/delete/$id': {
      id: '/_dashboardLayout/dev/delete/$id'
      path: '/delete/$id'
      fullPath: '/dev/delete/$id'
      preLoaderRoute: typeof DashboardLayoutDevDeleteIdImport
      parentRoute: typeof DashboardLayoutDevImport
    }
    '/_dashboardLayout/dev/detail/$id': {
      id: '/_dashboardLayout/dev/detail/$id'
      path: '/detail/$id'
      fullPath: '/dev/detail/$id'
      preLoaderRoute: typeof DashboardLayoutDevDetailIdImport
      parentRoute: typeof DashboardLayoutDevImport
    }
    '/_dashboardLayout/dev/edit/$id': {
      id: '/_dashboardLayout/dev/edit/$id'
      path: '/edit/$id'
      fullPath: '/dev/edit/$id'
      preLoaderRoute: typeof DashboardLayoutDevEditIdImport
      parentRoute: typeof DashboardLayoutDevImport
    }
    '/_dashboardLayout/users/delete/$userId': {
      id: '/_dashboardLayout/users/delete/$userId'
      path: '/delete/$userId'
      fullPath: '/users/delete/$userId'
      preLoaderRoute: typeof DashboardLayoutUsersDeleteUserIdImport
      parentRoute: typeof DashboardLayoutUsersImport
    }
    '/_dashboardLayout/users/detail/$userId': {
      id: '/_dashboardLayout/users/detail/$userId'
      path: '/detail/$userId'
      fullPath: '/users/detail/$userId'
      preLoaderRoute: typeof DashboardLayoutUsersDetailUserIdImport
      parentRoute: typeof DashboardLayoutUsersImport
    }
    '/_dashboardLayout/users/edit/$userId': {
      id: '/_dashboardLayout/users/edit/$userId'
      path: '/edit/$userId'
      fullPath: '/users/edit/$userId'
      preLoaderRoute: typeof DashboardLayoutUsersEditUserIdImport
      parentRoute: typeof DashboardLayoutUsersImport
    }
  }
}

// Create and export the route tree

interface DashboardLayoutDevRouteChildren {
  DashboardLayoutDevCreateRoute: typeof DashboardLayoutDevCreateRoute
  DashboardLayoutDevMultiSelectRoute: typeof DashboardLayoutDevMultiSelectRoute
  DashboardLayoutDevDeleteIdRoute: typeof DashboardLayoutDevDeleteIdRoute
  DashboardLayoutDevDetailIdRoute: typeof DashboardLayoutDevDetailIdRoute
  DashboardLayoutDevEditIdRoute: typeof DashboardLayoutDevEditIdRoute
}

const DashboardLayoutDevRouteChildren: DashboardLayoutDevRouteChildren = {
  DashboardLayoutDevCreateRoute: DashboardLayoutDevCreateRoute,
  DashboardLayoutDevMultiSelectRoute: DashboardLayoutDevMultiSelectRoute,
  DashboardLayoutDevDeleteIdRoute: DashboardLayoutDevDeleteIdRoute,
  DashboardLayoutDevDetailIdRoute: DashboardLayoutDevDetailIdRoute,
  DashboardLayoutDevEditIdRoute: DashboardLayoutDevEditIdRoute,
}

const DashboardLayoutDevRouteWithChildren =
  DashboardLayoutDevRoute._addFileChildren(DashboardLayoutDevRouteChildren)

interface DashboardLayoutRolesRouteChildren {
  DashboardLayoutRolesCreateRoute: typeof DashboardLayoutRolesCreateRoute
}

const DashboardLayoutRolesRouteChildren: DashboardLayoutRolesRouteChildren = {
  DashboardLayoutRolesCreateRoute: DashboardLayoutRolesCreateRoute,
}

const DashboardLayoutRolesRouteWithChildren =
  DashboardLayoutRolesRoute._addFileChildren(DashboardLayoutRolesRouteChildren)

interface DashboardLayoutUsersRouteChildren {
  DashboardLayoutUsersCreateRoute: typeof DashboardLayoutUsersCreateRoute
  DashboardLayoutUsersDeleteUserIdRoute: typeof DashboardLayoutUsersDeleteUserIdRoute
  DashboardLayoutUsersDetailUserIdRoute: typeof DashboardLayoutUsersDetailUserIdRoute
  DashboardLayoutUsersEditUserIdRoute: typeof DashboardLayoutUsersEditUserIdRoute
}

const DashboardLayoutUsersRouteChildren: DashboardLayoutUsersRouteChildren = {
  DashboardLayoutUsersCreateRoute: DashboardLayoutUsersCreateRoute,
  DashboardLayoutUsersDeleteUserIdRoute: DashboardLayoutUsersDeleteUserIdRoute,
  DashboardLayoutUsersDetailUserIdRoute: DashboardLayoutUsersDetailUserIdRoute,
  DashboardLayoutUsersEditUserIdRoute: DashboardLayoutUsersEditUserIdRoute,
}

const DashboardLayoutUsersRouteWithChildren =
  DashboardLayoutUsersRoute._addFileChildren(DashboardLayoutUsersRouteChildren)

interface DashboardLayoutRouteChildren {
  DashboardLayoutDevRoute: typeof DashboardLayoutDevRouteWithChildren
  DashboardLayoutRolesRoute: typeof DashboardLayoutRolesRouteWithChildren
  DashboardLayoutUsersRoute: typeof DashboardLayoutUsersRouteWithChildren
  DashboardLayoutDashboardIndexRoute: typeof DashboardLayoutDashboardIndexRoute
  DashboardLayoutTimetableIndexRoute: typeof DashboardLayoutTimetableIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutDevRoute: DashboardLayoutDevRouteWithChildren,
  DashboardLayoutRolesRoute: DashboardLayoutRolesRouteWithChildren,
  DashboardLayoutUsersRoute: DashboardLayoutUsersRouteWithChildren,
  DashboardLayoutDashboardIndexRoute: DashboardLayoutDashboardIndexRoute,
  DashboardLayoutTimetableIndexRoute: DashboardLayoutTimetableIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/403': typeof R403Route
  '': typeof DashboardLayoutRouteWithChildren
  '/dev': typeof DashboardLayoutDevRouteWithChildren
  '/roles': typeof DashboardLayoutRolesRouteWithChildren
  '/users': typeof DashboardLayoutUsersRouteWithChildren
  '/login': typeof LoginIndexLazyRoute
  '/logout': typeof LogoutIndexLazyRoute
  '/dev/create': typeof DashboardLayoutDevCreateRoute
  '/dev/multi-select': typeof DashboardLayoutDevMultiSelectRoute
  '/roles/create': typeof DashboardLayoutRolesCreateRoute
  '/users/create': typeof DashboardLayoutUsersCreateRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/timetable': typeof DashboardLayoutTimetableIndexRoute
  '/dev/delete/$id': typeof DashboardLayoutDevDeleteIdRoute
  '/dev/detail/$id': typeof DashboardLayoutDevDetailIdRoute
  '/dev/edit/$id': typeof DashboardLayoutDevEditIdRoute
  '/users/delete/$userId': typeof DashboardLayoutUsersDeleteUserIdRoute
  '/users/detail/$userId': typeof DashboardLayoutUsersDetailUserIdRoute
  '/users/edit/$userId': typeof DashboardLayoutUsersEditUserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/403': typeof R403Route
  '': typeof DashboardLayoutRouteWithChildren
  '/dev': typeof DashboardLayoutDevRouteWithChildren
  '/roles': typeof DashboardLayoutRolesRouteWithChildren
  '/users': typeof DashboardLayoutUsersRouteWithChildren
  '/login': typeof LoginIndexLazyRoute
  '/logout': typeof LogoutIndexLazyRoute
  '/dev/create': typeof DashboardLayoutDevCreateRoute
  '/dev/multi-select': typeof DashboardLayoutDevMultiSelectRoute
  '/roles/create': typeof DashboardLayoutRolesCreateRoute
  '/users/create': typeof DashboardLayoutUsersCreateRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/timetable': typeof DashboardLayoutTimetableIndexRoute
  '/dev/delete/$id': typeof DashboardLayoutDevDeleteIdRoute
  '/dev/detail/$id': typeof DashboardLayoutDevDetailIdRoute
  '/dev/edit/$id': typeof DashboardLayoutDevEditIdRoute
  '/users/delete/$userId': typeof DashboardLayoutUsersDeleteUserIdRoute
  '/users/detail/$userId': typeof DashboardLayoutUsersDetailUserIdRoute
  '/users/edit/$userId': typeof DashboardLayoutUsersEditUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/403': typeof R403Route
  '/_dashboardLayout': typeof DashboardLayoutRouteWithChildren
  '/_dashboardLayout/dev': typeof DashboardLayoutDevRouteWithChildren
  '/_dashboardLayout/roles': typeof DashboardLayoutRolesRouteWithChildren
  '/_dashboardLayout/users': typeof DashboardLayoutUsersRouteWithChildren
  '/login/': typeof LoginIndexLazyRoute
  '/logout/': typeof LogoutIndexLazyRoute
  '/_dashboardLayout/dev/create': typeof DashboardLayoutDevCreateRoute
  '/_dashboardLayout/dev/multi-select': typeof DashboardLayoutDevMultiSelectRoute
  '/_dashboardLayout/roles/create': typeof DashboardLayoutRolesCreateRoute
  '/_dashboardLayout/users/create': typeof DashboardLayoutUsersCreateRoute
  '/_dashboardLayout/dashboard/': typeof DashboardLayoutDashboardIndexRoute
  '/_dashboardLayout/timetable/': typeof DashboardLayoutTimetableIndexRoute
  '/_dashboardLayout/dev/delete/$id': typeof DashboardLayoutDevDeleteIdRoute
  '/_dashboardLayout/dev/detail/$id': typeof DashboardLayoutDevDetailIdRoute
  '/_dashboardLayout/dev/edit/$id': typeof DashboardLayoutDevEditIdRoute
  '/_dashboardLayout/users/delete/$userId': typeof DashboardLayoutUsersDeleteUserIdRoute
  '/_dashboardLayout/users/detail/$userId': typeof DashboardLayoutUsersDetailUserIdRoute
  '/_dashboardLayout/users/edit/$userId': typeof DashboardLayoutUsersEditUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | ''
    | '/dev'
    | '/roles'
    | '/users'
    | '/login'
    | '/logout'
    | '/dev/create'
    | '/dev/multi-select'
    | '/roles/create'
    | '/users/create'
    | '/dashboard'
    | '/timetable'
    | '/dev/delete/$id'
    | '/dev/detail/$id'
    | '/dev/edit/$id'
    | '/users/delete/$userId'
    | '/users/detail/$userId'
    | '/users/edit/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | ''
    | '/dev'
    | '/roles'
    | '/users'
    | '/login'
    | '/logout'
    | '/dev/create'
    | '/dev/multi-select'
    | '/roles/create'
    | '/users/create'
    | '/dashboard'
    | '/timetable'
    | '/dev/delete/$id'
    | '/dev/detail/$id'
    | '/dev/edit/$id'
    | '/users/delete/$userId'
    | '/users/detail/$userId'
    | '/users/edit/$userId'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_dashboardLayout'
    | '/_dashboardLayout/dev'
    | '/_dashboardLayout/roles'
    | '/_dashboardLayout/users'
    | '/login/'
    | '/logout/'
    | '/_dashboardLayout/dev/create'
    | '/_dashboardLayout/dev/multi-select'
    | '/_dashboardLayout/roles/create'
    | '/_dashboardLayout/users/create'
    | '/_dashboardLayout/dashboard/'
    | '/_dashboardLayout/timetable/'
    | '/_dashboardLayout/dev/delete/$id'
    | '/_dashboardLayout/dev/detail/$id'
    | '/_dashboardLayout/dev/edit/$id'
    | '/_dashboardLayout/users/delete/$userId'
    | '/_dashboardLayout/users/detail/$userId'
    | '/_dashboardLayout/users/edit/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  R403Route: typeof R403Route
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
  LogoutIndexLazyRoute: typeof LogoutIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  R403Route: R403Route,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
  LogoutIndexLazyRoute: LogoutIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/403",
        "/_dashboardLayout",
        "/login/",
        "/logout/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/403": {
      "filePath": "403.tsx"
    },
    "/_dashboardLayout": {
      "filePath": "_dashboardLayout.tsx",
      "children": [
        "/_dashboardLayout/dev",
        "/_dashboardLayout/roles",
        "/_dashboardLayout/users",
        "/_dashboardLayout/dashboard/",
        "/_dashboardLayout/timetable/"
      ]
    },
    "/_dashboardLayout/dev": {
      "filePath": "_dashboardLayout/dev.tsx",
      "parent": "/_dashboardLayout",
      "children": [
        "/_dashboardLayout/dev/create",
        "/_dashboardLayout/dev/multi-select",
        "/_dashboardLayout/dev/delete/$id",
        "/_dashboardLayout/dev/detail/$id",
        "/_dashboardLayout/dev/edit/$id"
      ]
    },
    "/_dashboardLayout/roles": {
      "filePath": "_dashboardLayout/roles.tsx",
      "parent": "/_dashboardLayout",
      "children": [
        "/_dashboardLayout/roles/create"
      ]
    },
    "/_dashboardLayout/users": {
      "filePath": "_dashboardLayout/users.tsx",
      "parent": "/_dashboardLayout",
      "children": [
        "/_dashboardLayout/users/create",
        "/_dashboardLayout/users/delete/$userId",
        "/_dashboardLayout/users/detail/$userId",
        "/_dashboardLayout/users/edit/$userId"
      ]
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    },
    "/logout/": {
      "filePath": "logout/index.lazy.tsx"
    },
    "/_dashboardLayout/dev/create": {
      "filePath": "_dashboardLayout/dev/create.tsx",
      "parent": "/_dashboardLayout/dev"
    },
    "/_dashboardLayout/dev/multi-select": {
      "filePath": "_dashboardLayout/dev/multi-select.tsx",
      "parent": "/_dashboardLayout/dev"
    },
    "/_dashboardLayout/roles/create": {
      "filePath": "_dashboardLayout/roles/create.tsx",
      "parent": "/_dashboardLayout/roles"
    },
    "/_dashboardLayout/users/create": {
      "filePath": "_dashboardLayout/users/create.tsx",
      "parent": "/_dashboardLayout/users"
    },
    "/_dashboardLayout/dashboard/": {
      "filePath": "_dashboardLayout/dashboard/index.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/timetable/": {
      "filePath": "_dashboardLayout/timetable/index.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/dev/delete/$id": {
      "filePath": "_dashboardLayout/dev/delete.$id.tsx",
      "parent": "/_dashboardLayout/dev"
    },
    "/_dashboardLayout/dev/detail/$id": {
      "filePath": "_dashboardLayout/dev/detail.$id.tsx",
      "parent": "/_dashboardLayout/dev"
    },
    "/_dashboardLayout/dev/edit/$id": {
      "filePath": "_dashboardLayout/dev/edit.$id.tsx",
      "parent": "/_dashboardLayout/dev"
    },
    "/_dashboardLayout/users/delete/$userId": {
      "filePath": "_dashboardLayout/users/delete.$userId.tsx",
      "parent": "/_dashboardLayout/users"
    },
    "/_dashboardLayout/users/detail/$userId": {
      "filePath": "_dashboardLayout/users/detail.$userId.tsx",
      "parent": "/_dashboardLayout/users"
    },
    "/_dashboardLayout/users/edit/$userId": {
      "filePath": "_dashboardLayout/users/edit.$userId.tsx",
      "parent": "/_dashboardLayout/users"
    }
  }
}
ROUTE_MANIFEST_END */
