name: Production Deployment

on:
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: production-deployment
    cancel-in-progress: true

jobs:
    build-and-deploy:
        runs-on: pc-chesa
        timeout-minutes: 45
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Build and push backend image
              run: |
                  docker build \
                  -f apps/backend/dockerfile \
                  -t localhost:5001/personal-dashboard/backend:latest \
                  .
                  docker push localhost:5001/personal-dashboard/backend:latest

            - name: Build and push frontend image
              run: |
                  docker build \
                  -f apps/frontend/dockerfile \
                  --build-arg VITE_BACKEND_BASE_URL=http://api.dashboard.lan \
                  -t localhost:5001/personal-dashboard/frontend:latest \
                  .
                  docker push localhost:5001/personal-dashboard/frontend:latest

            - name: Deploy backend to Dokploy
              run: |
                  curl -X 'POST' \
                  'http://100.115.79.97:3000/api/trpc/application.redeploy' \
                  -H 'accept: application/json' \
                  -H 'x-api-key: ${{ secrets.DOKPLOY_API_KEY }}' \
                  -H 'Content-Type: application/json' \
                  -d '{
                      "json":{
                          "applicationId": "Nc8bXeEpBiIH3gvAgXysu"
                      }
                  }'

            - name: Deploy frontend to Dokploy
              run: |
                  curl -X 'POST' \
                  'http://100.115.79.97:3000/api/trpc/application.redeploy' \
                  -H 'accept: application/json' \
                  -H 'x-api-key: ${{ secrets.DOKPLOY_API_KEY }}' \
                  -H 'Content-Type: application/json' \
                  -d '{
                      "json":{
                          "applicationId": "-sybwlonIbzrIH69BeGEC"
                      }
                  }'
